repos:
- hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace
  repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.3.0
- hooks:
  - id: commitizen
    stages:
    - commit-msg
  repo: https://github.com/commitizen-tools/commitizen
  rev: v2.28.0
- hooks:
  - args:
    - --skip-string-normalization
    id: black
  repo: https://github.com/psf/black
  rev: 22.6.0
- hooks:
  - args:
    - --profile=black
    - --src=src
    id: isort
  repo: https://github.com/PyCQA/isort
  rev: 5.10.1
